// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: aggregator/messages/messages.proto

package messages

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Currency int32

const (
	Currency_USD Currency = 0
	Currency_RUB Currency = 1
)

// Enum value maps for Currency.
var (
	Currency_name = map[int32]string{
		0: "USD",
		1: "RUB",
	}
	Currency_value = map[string]int32{
		"USD": 0,
		"RUB": 1,
	}
)

func (x Currency) Enum() *Currency {
	p := new(Currency)
	*p = x
	return p
}

func (x Currency) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Currency) Descriptor() protoreflect.EnumDescriptor {
	return file_aggregator_messages_messages_proto_enumTypes[0].Descriptor()
}

func (Currency) Type() protoreflect.EnumType {
	return &file_aggregator_messages_messages_proto_enumTypes[0]
}

func (x Currency) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Currency.Descriptor instead.
func (Currency) EnumDescriptor() ([]byte, []int) {
	return file_aggregator_messages_messages_proto_rawDescGZIP(), []int{0}
}

type PortfolioRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Options map[string]string `protobuf:"bytes,1,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *PortfolioRequest) Reset() {
	*x = PortfolioRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aggregator_messages_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PortfolioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortfolioRequest) ProtoMessage() {}

func (x *PortfolioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aggregator_messages_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortfolioRequest.ProtoReflect.Descriptor instead.
func (*PortfolioRequest) Descriptor() ([]byte, []int) {
	return file_aggregator_messages_messages_proto_rawDescGZIP(), []int{0}
}

func (x *PortfolioRequest) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

type PortfolioReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *PortfolioStats `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *PortfolioReply) Reset() {
	*x = PortfolioReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aggregator_messages_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PortfolioReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortfolioReply) ProtoMessage() {}

func (x *PortfolioReply) ProtoReflect() protoreflect.Message {
	mi := &file_aggregator_messages_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortfolioReply.ProtoReflect.Descriptor instead.
func (*PortfolioReply) Descriptor() ([]byte, []int) {
	return file_aggregator_messages_messages_proto_rawDescGZIP(), []int{1}
}

func (x *PortfolioReply) GetData() *PortfolioStats {
	if x != nil {
		return x.Data
	}
	return nil
}

type PortfolioStats struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Currency Currency         `protobuf:"varint,1,opt,name=currency,proto3,enum=Currency" json:"currency,omitempty"`
	Date     int64            `protobuf:"varint,2,opt,name=date,proto3" json:"date,omitempty"`
	Stocks   []*StockData     `protobuf:"bytes,3,rep,name=stocks,proto3" json:"stocks,omitempty"`
	Totals   *PortfolioTotals `protobuf:"bytes,4,opt,name=totals,proto3" json:"totals,omitempty"`
}

func (x *PortfolioStats) Reset() {
	*x = PortfolioStats{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aggregator_messages_messages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PortfolioStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortfolioStats) ProtoMessage() {}

func (x *PortfolioStats) ProtoReflect() protoreflect.Message {
	mi := &file_aggregator_messages_messages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortfolioStats.ProtoReflect.Descriptor instead.
func (*PortfolioStats) Descriptor() ([]byte, []int) {
	return file_aggregator_messages_messages_proto_rawDescGZIP(), []int{2}
}

func (x *PortfolioStats) GetCurrency() Currency {
	if x != nil {
		return x.Currency
	}
	return Currency_USD
}

func (x *PortfolioStats) GetDate() int64 {
	if x != nil {
		return x.Date
	}
	return 0
}

func (x *PortfolioStats) GetStocks() []*StockData {
	if x != nil {
		return x.Stocks
	}
	return nil
}

func (x *PortfolioStats) GetTotals() *PortfolioTotals {
	if x != nil {
		return x.Totals
	}
	return nil
}

type StockData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids     map[string]string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Name    string            `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Balance float64           `protobuf:"fixed64,3,opt,name=balance,proto3" json:"balance,omitempty"`
	Price   float64           `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	Yield   float64           `protobuf:"fixed64,5,opt,name=yield,proto3" json:"yield,omitempty"`
}

func (x *StockData) Reset() {
	*x = StockData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aggregator_messages_messages_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StockData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockData) ProtoMessage() {}

func (x *StockData) ProtoReflect() protoreflect.Message {
	mi := &file_aggregator_messages_messages_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockData.ProtoReflect.Descriptor instead.
func (*StockData) Descriptor() ([]byte, []int) {
	return file_aggregator_messages_messages_proto_rawDescGZIP(), []int{3}
}

func (x *StockData) GetIds() map[string]string {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *StockData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StockData) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *StockData) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *StockData) GetYield() float64 {
	if x != nil {
		return x.Yield
	}
	return 0
}

type PortfolioTotals struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Invested float64 `protobuf:"fixed64,1,opt,name=invested,proto3" json:"invested,omitempty"`
	Yield    float64 `protobuf:"fixed64,2,opt,name=yield,proto3" json:"yield,omitempty"`
}

func (x *PortfolioTotals) Reset() {
	*x = PortfolioTotals{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aggregator_messages_messages_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PortfolioTotals) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortfolioTotals) ProtoMessage() {}

func (x *PortfolioTotals) ProtoReflect() protoreflect.Message {
	mi := &file_aggregator_messages_messages_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortfolioTotals.ProtoReflect.Descriptor instead.
func (*PortfolioTotals) Descriptor() ([]byte, []int) {
	return file_aggregator_messages_messages_proto_rawDescGZIP(), []int{4}
}

func (x *PortfolioTotals) GetInvested() float64 {
	if x != nil {
		return x.Invested
	}
	return 0
}

func (x *PortfolioTotals) GetYield() float64 {
	if x != nil {
		return x.Yield
	}
	return 0
}

var File_aggregator_messages_messages_proto protoreflect.FileDescriptor

var file_aggregator_messages_messages_proto_rawDesc = []byte{
	0x0a, 0x22, 0x61, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x73, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x88, 0x01, 0x0a, 0x10, 0x50, 0x6f, 0x72, 0x74, 0x66, 0x6f, 0x6c,
	0x69, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x38, 0x0a, 0x07, 0x6f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x50, 0x6f, 0x72,
	0x74, 0x66, 0x6f, 0x6c, 0x69, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x6f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x1a, 0x3a, 0x0a, 0x0c, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22,
	0x35, 0x0a, 0x0e, 0x50, 0x6f, 0x72, 0x74, 0x66, 0x6f, 0x6c, 0x69, 0x6f, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x23, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x50, 0x6f, 0x72, 0x74, 0x66, 0x6f, 0x6c, 0x69, 0x6f, 0x53, 0x74, 0x61, 0x74, 0x73,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x99, 0x01, 0x0a, 0x0e, 0x50, 0x6f, 0x72, 0x74, 0x66,
	0x6f, 0x6c, 0x69, 0x6f, 0x53, 0x74, 0x61, 0x74, 0x73, 0x12, 0x25, 0x0a, 0x08, 0x63, 0x75, 0x72,
	0x72, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x09, 0x2e, 0x43, 0x75,
	0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x52, 0x08, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79,
	0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x65, 0x12, 0x22, 0x0a, 0x06, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x73, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x44, 0x61, 0x74, 0x61,
	0x52, 0x06, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x73, 0x12, 0x28, 0x0a, 0x06, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x50, 0x6f, 0x72, 0x74, 0x66,
	0x6f, 0x6c, 0x69, 0x6f, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x73, 0x52, 0x06, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x73, 0x22, 0xc4, 0x01, 0x0a, 0x09, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x44, 0x61, 0x74, 0x61,
	0x12, 0x25, 0x0a, 0x03, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e,
	0x53, 0x74, 0x6f, 0x63, 0x6b, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x49, 0x64, 0x73, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x52, 0x03, 0x69, 0x64, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x62,
	0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x07, 0x62, 0x61,
	0x6c, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x79,
	0x69, 0x65, 0x6c, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x79, 0x69, 0x65, 0x6c,
	0x64, 0x1a, 0x36, 0x0a, 0x08, 0x49, 0x64, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x43, 0x0a, 0x0f, 0x50, 0x6f, 0x72,
	0x74, 0x66, 0x6f, 0x6c, 0x69, 0x6f, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x73, 0x12, 0x1a, 0x0a, 0x08,
	0x69, 0x6e, 0x76, 0x65, 0x73, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08,
	0x69, 0x6e, 0x76, 0x65, 0x73, 0x74, 0x65, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x79, 0x69, 0x65, 0x6c,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x79, 0x69, 0x65, 0x6c, 0x64, 0x2a, 0x1c,
	0x0a, 0x08, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x07, 0x0a, 0x03, 0x55, 0x53,
	0x44, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x52, 0x55, 0x42, 0x10, 0x01, 0x32, 0x41, 0x0a, 0x09,
	0x50, 0x6f, 0x72, 0x74, 0x66, 0x6f, 0x6c, 0x69, 0x6f, 0x12, 0x34, 0x0a, 0x0c, 0x47, 0x65, 0x74,
	0x50, 0x6f, 0x72, 0x74, 0x66, 0x6f, 0x6c, 0x69, 0x6f, 0x12, 0x11, 0x2e, 0x50, 0x6f, 0x72, 0x74,
	0x66, 0x6f, 0x6c, 0x69, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x50,
	0x6f, 0x72, 0x74, 0x66, 0x6f, 0x6c, 0x69, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42,
	0x34, 0x5a, 0x32, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x66, 0x61,
	0x62, 0x72, 0x69, 0x74, 0x73, 0x69, 0x75, 0x73, 0x2f, 0x69, 0x6e, 0x76, 0x65, 0x73, 0x74, 0x6f,
	0x72, 0x2f, 0x61, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_aggregator_messages_messages_proto_rawDescOnce sync.Once
	file_aggregator_messages_messages_proto_rawDescData = file_aggregator_messages_messages_proto_rawDesc
)

func file_aggregator_messages_messages_proto_rawDescGZIP() []byte {
	file_aggregator_messages_messages_proto_rawDescOnce.Do(func() {
		file_aggregator_messages_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_aggregator_messages_messages_proto_rawDescData)
	})
	return file_aggregator_messages_messages_proto_rawDescData
}

var file_aggregator_messages_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_aggregator_messages_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_aggregator_messages_messages_proto_goTypes = []interface{}{
	(Currency)(0),            // 0: Currency
	(*PortfolioRequest)(nil), // 1: PortfolioRequest
	(*PortfolioReply)(nil),   // 2: PortfolioReply
	(*PortfolioStats)(nil),   // 3: PortfolioStats
	(*StockData)(nil),        // 4: StockData
	(*PortfolioTotals)(nil),  // 5: PortfolioTotals
	nil,                      // 6: PortfolioRequest.OptionsEntry
	nil,                      // 7: StockData.IdsEntry
}
var file_aggregator_messages_messages_proto_depIdxs = []int32{
	6, // 0: PortfolioRequest.options:type_name -> PortfolioRequest.OptionsEntry
	3, // 1: PortfolioReply.data:type_name -> PortfolioStats
	0, // 2: PortfolioStats.currency:type_name -> Currency
	4, // 3: PortfolioStats.stocks:type_name -> StockData
	5, // 4: PortfolioStats.totals:type_name -> PortfolioTotals
	7, // 5: StockData.ids:type_name -> StockData.IdsEntry
	1, // 6: Portfolio.GetPortfolio:input_type -> PortfolioRequest
	2, // 7: Portfolio.GetPortfolio:output_type -> PortfolioReply
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_aggregator_messages_messages_proto_init() }
func file_aggregator_messages_messages_proto_init() {
	if File_aggregator_messages_messages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_aggregator_messages_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PortfolioRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aggregator_messages_messages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PortfolioReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aggregator_messages_messages_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PortfolioStats); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aggregator_messages_messages_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StockData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aggregator_messages_messages_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PortfolioTotals); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_aggregator_messages_messages_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_aggregator_messages_messages_proto_goTypes,
		DependencyIndexes: file_aggregator_messages_messages_proto_depIdxs,
		EnumInfos:         file_aggregator_messages_messages_proto_enumTypes,
		MessageInfos:      file_aggregator_messages_messages_proto_msgTypes,
	}.Build()
	File_aggregator_messages_messages_proto = out.File
	file_aggregator_messages_messages_proto_rawDesc = nil
	file_aggregator_messages_messages_proto_goTypes = nil
	file_aggregator_messages_messages_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PortfolioClient is the client API for Portfolio service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PortfolioClient interface {
	GetPortfolio(ctx context.Context, in *PortfolioRequest, opts ...grpc.CallOption) (*PortfolioReply, error)
}

type portfolioClient struct {
	cc grpc.ClientConnInterface
}

func NewPortfolioClient(cc grpc.ClientConnInterface) PortfolioClient {
	return &portfolioClient{cc}
}

func (c *portfolioClient) GetPortfolio(ctx context.Context, in *PortfolioRequest, opts ...grpc.CallOption) (*PortfolioReply, error) {
	out := new(PortfolioReply)
	err := c.cc.Invoke(ctx, "/Portfolio/GetPortfolio", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PortfolioServer is the server API for Portfolio service.
type PortfolioServer interface {
	GetPortfolio(context.Context, *PortfolioRequest) (*PortfolioReply, error)
}

// UnimplementedPortfolioServer can be embedded to have forward compatible implementations.
type UnimplementedPortfolioServer struct {
}

func (*UnimplementedPortfolioServer) GetPortfolio(context.Context, *PortfolioRequest) (*PortfolioReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPortfolio not implemented")
}

func RegisterPortfolioServer(s *grpc.Server, srv PortfolioServer) {
	s.RegisterService(&_Portfolio_serviceDesc, srv)
}

func _Portfolio_GetPortfolio_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PortfolioRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServer).GetPortfolio(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Portfolio/GetPortfolio",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServer).GetPortfolio(ctx, req.(*PortfolioRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Portfolio_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Portfolio",
	HandlerType: (*PortfolioServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPortfolio",
			Handler:    _Portfolio_GetPortfolio_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "aggregator/messages/messages.proto",
}
