// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: aggregator/messages/messages.proto

package messages

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type PortfolioRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User string `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *PortfolioRequest) Reset() {
	*x = PortfolioRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aggregator_messages_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PortfolioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortfolioRequest) ProtoMessage() {}

func (x *PortfolioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aggregator_messages_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortfolioRequest.ProtoReflect.Descriptor instead.
func (*PortfolioRequest) Descriptor() ([]byte, []int) {
	return file_aggregator_messages_messages_proto_rawDescGZIP(), []int{0}
}

func (x *PortfolioRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

type PortfolioReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data string `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *PortfolioReply) Reset() {
	*x = PortfolioReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aggregator_messages_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PortfolioReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortfolioReply) ProtoMessage() {}

func (x *PortfolioReply) ProtoReflect() protoreflect.Message {
	mi := &file_aggregator_messages_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortfolioReply.ProtoReflect.Descriptor instead.
func (*PortfolioReply) Descriptor() ([]byte, []int) {
	return file_aggregator_messages_messages_proto_rawDescGZIP(), []int{1}
}

func (x *PortfolioReply) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

var File_aggregator_messages_messages_proto protoreflect.FileDescriptor

var file_aggregator_messages_messages_proto_rawDesc = []byte{
	0x0a, 0x22, 0x61, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x73, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x26, 0x0a, 0x10, 0x50, 0x6f, 0x72, 0x74, 0x66, 0x6f, 0x6c, 0x69,
	0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x22, 0x24, 0x0a, 0x0e,
	0x50, 0x6f, 0x72, 0x74, 0x66, 0x6f, 0x6c, 0x69, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x32, 0x41, 0x0a, 0x09, 0x50, 0x6f, 0x72, 0x74, 0x66, 0x6f, 0x6c, 0x69, 0x6f, 0x12,
	0x34, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x50, 0x6f, 0x72, 0x74, 0x66, 0x6f, 0x6c, 0x69, 0x6f, 0x12,
	0x11, 0x2e, 0x50, 0x6f, 0x72, 0x74, 0x66, 0x6f, 0x6c, 0x69, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x50, 0x6f, 0x72, 0x74, 0x66, 0x6f, 0x6c, 0x69, 0x6f, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x34, 0x5a, 0x32, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x66, 0x61, 0x62, 0x72, 0x69, 0x74, 0x73, 0x69, 0x75, 0x73, 0x2f, 0x69,
	0x6e, 0x76, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x2f, 0x61, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74,
	0x6f, 0x72, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_aggregator_messages_messages_proto_rawDescOnce sync.Once
	file_aggregator_messages_messages_proto_rawDescData = file_aggregator_messages_messages_proto_rawDesc
)

func file_aggregator_messages_messages_proto_rawDescGZIP() []byte {
	file_aggregator_messages_messages_proto_rawDescOnce.Do(func() {
		file_aggregator_messages_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_aggregator_messages_messages_proto_rawDescData)
	})
	return file_aggregator_messages_messages_proto_rawDescData
}

var file_aggregator_messages_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_aggregator_messages_messages_proto_goTypes = []interface{}{
	(*PortfolioRequest)(nil), // 0: PortfolioRequest
	(*PortfolioReply)(nil),   // 1: PortfolioReply
}
var file_aggregator_messages_messages_proto_depIdxs = []int32{
	0, // 0: Portfolio.GetPortfolio:input_type -> PortfolioRequest
	1, // 1: Portfolio.GetPortfolio:output_type -> PortfolioReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_aggregator_messages_messages_proto_init() }
func file_aggregator_messages_messages_proto_init() {
	if File_aggregator_messages_messages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_aggregator_messages_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PortfolioRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aggregator_messages_messages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PortfolioReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_aggregator_messages_messages_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_aggregator_messages_messages_proto_goTypes,
		DependencyIndexes: file_aggregator_messages_messages_proto_depIdxs,
		MessageInfos:      file_aggregator_messages_messages_proto_msgTypes,
	}.Build()
	File_aggregator_messages_messages_proto = out.File
	file_aggregator_messages_messages_proto_rawDesc = nil
	file_aggregator_messages_messages_proto_goTypes = nil
	file_aggregator_messages_messages_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PortfolioClient is the client API for Portfolio service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PortfolioClient interface {
	GetPortfolio(ctx context.Context, in *PortfolioRequest, opts ...grpc.CallOption) (*PortfolioReply, error)
}

type portfolioClient struct {
	cc grpc.ClientConnInterface
}

func NewPortfolioClient(cc grpc.ClientConnInterface) PortfolioClient {
	return &portfolioClient{cc}
}

func (c *portfolioClient) GetPortfolio(ctx context.Context, in *PortfolioRequest, opts ...grpc.CallOption) (*PortfolioReply, error) {
	out := new(PortfolioReply)
	err := c.cc.Invoke(ctx, "/Portfolio/GetPortfolio", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PortfolioServer is the server API for Portfolio service.
type PortfolioServer interface {
	GetPortfolio(context.Context, *PortfolioRequest) (*PortfolioReply, error)
}

// UnimplementedPortfolioServer can be embedded to have forward compatible implementations.
type UnimplementedPortfolioServer struct {
}

func (*UnimplementedPortfolioServer) GetPortfolio(context.Context, *PortfolioRequest) (*PortfolioReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPortfolio not implemented")
}

func RegisterPortfolioServer(s *grpc.Server, srv PortfolioServer) {
	s.RegisterService(&_Portfolio_serviceDesc, srv)
}

func _Portfolio_GetPortfolio_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PortfolioRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServer).GetPortfolio(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Portfolio/GetPortfolio",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServer).GetPortfolio(ctx, req.(*PortfolioRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Portfolio_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Portfolio",
	HandlerType: (*PortfolioServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPortfolio",
			Handler:    _Portfolio_GetPortfolio_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "aggregator/messages/messages.proto",
}
